name: 'Terraform'
on: [push]

defaults:
 run:
  working-directory: ./terraform
  
jobs:
  terraform_apply:
    if: github.ref == 'refs/heads/main' || contains(github.event.head_commit.message, '--apply_tf')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Fetch Terraform State
      uses: prewk/s3-cp-action@v2
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        source: 's3://whlsckr-terraform/terraform.tfstate'
        dest: './terraform.tfstate'
    - name: Verify Terraform version
      run: terraform --version

    - name: Terraform init
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: terraform init -input=false

    - name: Terraform validation
      run: terraform validate
    
    - name: Terraform apply      
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: terraform apply -auto-approve -input=false
    - name: Upload Terraform State
      uses: prewk/s3-cp-action@v2
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        dest: 's3://whlsckr-terraform/terraform.tfstate'
        source: './terraform.tfstate'
